### ISSUE TITLE
Disable line-merging for transportation linestrings with oneway tag

### ISSUE THREAD

**Issue by msbarry** [openmaptiles/planetiler-openmaptiles#10]
This planetiler profile currently merges transportation linestrings with the same tags, but this causes issues because it might reverse a linestring but not the `oneway` tag.  The medium-term fix is to improve the feature merge API in planetiler to be more flexible so you can specify here that it needs to flip the oneway tag when a linestring is reversed, but as a short term workaround we should disable line merging for features that have a oneway tag on them.

https://github.com/onthegomap/planetiler/issues/296

**Comment by lazaa32** [comment]
Should it be fixed in this OMT repo:
https://github.com/openmaptiles/planetiler-openmaptiles/blob/main/src/main/java/com/onthegomap/planetiler/openmaptiles/layers/Transportation.java#L537
or in PT-core:
https://github.com/onthegomap/planetiler/blob/main/planetiler-core/src/main/java/com/onthegomap/planetiler/FeatureMerge.java#L83
@msbarry ?

**Comment by msbarry** [comment]
There's a short term and medium-term fix.  In the short term, I think we should just disable line merging for any road with a oneway tag (or even just disable line merging entirely for transportation layer).  In the medium-term, we should improve FeatureMerge in pt-core to be smart enough to reverse the oneway tag when a line segment gets reversed.

**Comment by msbarry** [comment]
Sorry for the delay here, the short term fix (#40) should be implemented now.
