### ISSUE TITLE
Support POV admin0 NE boundaries

### ISSUE THREAD

**Issue by ZeLonewolf** [openmaptiles/planetiler-openmaptiles#67]
Natural Earth provides "POV" country boundary files. A "POV" boundary includes national boundaries as recognized by various countries. For example, a mapmaker building a map for a Chinese audience would want to display different boundaries than that for an Indian consumer.

https://www.naturalearthdata.com/downloads/10m-cultural-vectors/

I propose that planetiler have a command-line option which can select from one of the available POV files as a drop-in replacement for the standard 10m country boundary file.

**Comment by msbarry** [comment]
Cool! That would only impact low zoom boundaries though - it uses OSM for high zoom though. Could something equivalent be derived from OSM at high zooms?

**Comment by ZeLonewolf** [comment]
It's already present in the tiles!

For example, see the Dixon Entrance US/Canada boundary dispute:
[![image](https://user-images.githubusercontent.com/3254090/216762658-46558e98-d940-49fa-b13b-2c79138be8fe.png)](https://6ug7hetxl9.execute-api.us-east-2.amazonaws.com/data/v3/#5.94/55.29/-129.524)

Right now, a user desiring to render one or the other claim can do so only at high zoom.  For low zoom, they're stuck on the default Natural Earth polygons.

**Comment by msbarry** [comment]
got it, and does openmaptiles handle this yet?

**Comment by msbarry** [comment]
Also could another approach here be to use osm data at lower zooms instead of switching to natural earth in the first place? Then you could switch clientside without needing to regenerate.

**Comment by ZeLonewolf** [comment]
openmaptiles doesn't support NE POV files, and I'm not sure how you'd even make it work in the architecture. I'd also be in favor of running boundaries all the way up in OSM rather than using Natural Earth but so far I've been afraid to touch the openmpatiles boundary code :grimacing:

**Comment by msbarry** [comment]
Here's zoom 0 existing natural earth logic (left) vs. just OSM (right)

<img width="1487" alt="image" src="https://user-images.githubusercontent.com/1480504/216773993-f4cd8c5a-0037-4be1-a3e0-18dd643a6d0b.png">

zoom 1:

<img width="1490" alt="image" src="https://user-images.githubusercontent.com/1480504/216774041-129c97ab-a34e-41a5-9edc-b6244951dd54.png">

zoom 2:

<img width="1490" alt="image" src="https://user-images.githubusercontent.com/1480504/216774125-436a27fa-933c-43e4-aace-2e5db1cf8c76.png">

zoom 3:

<img width="1489" alt="image" src="https://user-images.githubusercontent.com/1480504/216774155-84dc3ff1-6914-4973-a35d-902422577832.png">

<img width="1489" alt="image" src="https://user-images.githubusercontent.com/1480504/216774233-52705c1f-a888-4de4-8b67-bb4c225fb14c.png">

zoom 4:

<img width="1494" alt="image" src="https://user-images.githubusercontent.com/1480504/216774298-ea1e26e2-6cc3-4334-a403-590156c99242.png">

tiles are also slightly smaller with NE:

```
0:01:00 DEB [mbtiles] - z0 avg:55k max:55k
0:01:00 DEB [mbtiles] - z1 avg:138k max:160k
0:01:00 DEB [mbtiles] - z2 avg:244k max:448k
0:01:00 DEB [mbtiles] - z3 avg:64k max:312k
0:01:00 DEB [mbtiles] - z4 avg:18k max:196k
0:01:00 DEB [mbtiles] - z5 avg:6.8k max:107k
0:01:00 DEB [mbtiles] - z6 avg:2.7k max:52k
```

over just OSM:

```
0:01:00 DEB [mbtiles] - z0 avg:67k max:67k
0:01:00 DEB [mbtiles] - z1 avg:151k max:188k
0:01:00 DEB [mbtiles] - z2 avg:250k max:488k
0:01:00 DEB [mbtiles] - z3 avg:67k max:329k
0:01:00 DEB [mbtiles] - z4 avg:20k max:209k
0:01:00 DEB [mbtiles] - z5 avg:6.8k max:107k
0:01:00 DEB [mbtiles] - z6 avg:2.7k max:52k
```

so it seems like the main thing you miss out on with osm-only approach is opinionated filtering of boundaries to avoid overwhelming the tiles/ui at lower zooms. Although I'd argue zoom level 1 and 2 have too much detail with current natural earth approach as well.

**Comment by ZeLonewolf** [comment]
From the screenshots, I'm led to believe that the subdivisions of Greenland are the only real outliers.

**Comment by msbarry** [comment]
OK I put out #71 to let you opt-into using OSM for boundaries at all zoom levels by adding the `--boundary-osm-only=true` argument when running planetiler.  Maybe we could try out that experimentally, perhaps makes some tweaks, and then suggest a change upstream to openmaptiles when we're happy with the result?

Overall the boundary handling is a mess and too slow to generalize to adding left/right labels for states, counties, towns, etc., I'd like to improve it with some built-in functionality in planetiler so that this repo just has to opt-into using that instead of implementing the boundary collection manually.  If you squint your eyes, you basically have a bunch of segments that are shared between region polygons and you want a flow something like this:

- collect all segments that are part of boundary relations
- create polygons from segments for each region
- use each polygon to label the region on one side of each of its boundary segments
- then decide to emit each border segment with a min zoom based on the min admin level of a region it's a part of, but also take into account the size of the region, to avoid emitting borders for tiny regions at low zooms.

Alternatively you might always want to emit every state border in a particular country, so you might make a decision based on the size of the country and number of regions it's divided into...? We might want to dig into how https://github.com/nvkelso/natural-earth-vector handles this and try to match it's logic.
